export async function up(knex) {
  await knex.raw(`
    CREATE TABLE users (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE groups (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE user_groups (
      user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      group_id INT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      PRIMARY KEY (user_id, group_id)
    );

    CREATE TABLE resources (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE TABLE resource_shares (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      resource_id INT NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
      share_type TEXT NOT NULL CHECK (share_type IN ('user', 'group', 'everyone')),
      user_id INT REFERENCES users(id) ON DELETE CASCADE,
      group_id INT REFERENCES groups(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      CHECK (
        (share_type = 'user' AND user_id IS NOT NULL AND group_id IS NULL) OR
        (share_type = 'group' AND group_id IS NOT NULL AND user_id IS NULL) OR
        (share_type = 'everyone' AND user_id IS NULL AND group_id IS NULL)
      ),
      UNIQUE (resource_id, share_type, user_id, group_id)
    );

    CREATE INDEX idx_user_groups_group_id ON user_groups(group_id);
    CREATE INDEX idx_user_groups_user_id ON user_groups(user_id);
    CREATE INDEX idx_resource_shares_resource_id ON resource_shares(resource_id);
    CREATE INDEX idx_resource_shares_user_id ON resource_shares(user_id) WHERE user_id IS NOT NULL;
    CREATE INDEX idx_resource_shares_group_id ON resource_shares(group_id) WHERE group_id IS NOT NULL;
    CREATE INDEX idx_resource_shared_globally ON resource_shares(resource_id) WHERE user_id IS NULL AND group_id IS NULL;
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS resource_shares;
    DROP TABLE IF EXISTS resources;
    DROP TABLE IF EXISTS user_groups;
    DROP TABLE IF EXISTS groups;
    DROP TABLE IF EXISTS users;
  `);
}
